"""add playground visits

Revision ID: 3b97f14c133c
Revises: 7818dcb0ae2b
Create Date: 2026-07-24 15:42:49.591001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b97f14c133c'
down_revision: Union[str, None] = '7818dcb0ae2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playground_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playground_id'], ['playgrounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playground_id', 'user_id', name='uq_playground_visit')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playground_visits')
    # ### end Alembic commands ###
