"""init playgrounds

Revision ID: 3f4aeb3be2ab
Revises: 
Create Date: 2026-07-21 15:48:03.587932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f4aeb3be2ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playgrounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('APARTMENT', 'NEIGHBORHOOD_PARK', 'CHILDRENS_PARK', 'SCHOOL', 'INDOOR', 'THEME', 'INCLUSIVE', 'RIVERSIDE', 'ETC', name='playground_type'), nullable=True),
    sa.Column('age_groups', postgresql.ARRAY(sa.Enum('INFANT', 'TODDLER', 'CHILD', 'PRETEEN', 'ALL_AGES', name='age_group')), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('directions', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('operating_hours', sa.String(length=200), nullable=True),
    sa.Column('closed_days', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Enum('PUBLIC_DATA', 'USER_SUBMITTED', name='playground_source'), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playground_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playground_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playground_id'], ['playgrounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playground_images')
    op.drop_table('playgrounds')
    # ### end Alembic commands ###
