"""phone auth, nickname, likes, comments

Revision ID: c0173754d3f6
Revises: f322226a5fd5
Create Date: 2026-07-22 09:26:14.813754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0173754d3f6'
down_revision: Union[str, None] = 'f322226a5fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playground_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playground_id'], ['playgrounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playground_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playground_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playground_id'], ['playgrounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playground_id', 'user_id', name='uq_playground_like')
    )
    # 이메일 -> 휴대폰/닉네임으로 로그인 방식이 바뀌면서 기존 계정 정보는 그대로 이전할 수 없다.
    # 아직 로컬 개발용 테스트 계정뿐이므로 초기화한다.
    op.execute("UPDATE playgrounds SET submitted_by_id = NULL")
    op.execute("DELETE FROM users")

    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_unique_constraint(None, 'users', ['nickname'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'phone')
    op.drop_table('playground_likes')
    op.drop_table('playground_comments')
    # ### end Alembic commands ###
