"""add playground views table

Revision ID: c45c090031b5
Revises: e24684e82493
Create Date: 2026-08-05 10:15:27.946271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45c090031b5'
down_revision: Union[str, None] = 'e24684e82493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playground_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playground_id'], ['playgrounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_playground_views_playground_id_viewed_at', 'playground_views', ['playground_id', 'viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playground_views_playground_id_viewed_at', table_name='playground_views')
    op.drop_table('playground_views')
    # ### end Alembic commands ###
