"""add safety info and equipment fields

Revision ID: c81f68eb6a51
Revises: c0173754d3f6
Create Date: 2026-07-22 13:11:44.212986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c81f68eb6a51'
down_revision: Union[str, None] = 'c0173754d3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    surface_type = sa.Enum('URETHANE', 'SAND', 'GRASS', 'RUBBER_CHIP', 'SOIL', name='surface_type')
    shade_level = sa.Enum('SUFFICIENT', 'MODERATE', 'NONE', name='shade_level')
    restroom_type = sa.Enum('NONE', 'AVAILABLE', 'AVAILABLE_WITH_DIAPER_TABLE', name='restroom_type')
    parking_type = sa.Enum('NONE', 'FREE', 'PAID', name='parking_type')
    fence_type = sa.Enum('FULL', 'PARTIAL', 'NONE', name='fence_type')
    equipment_type = sa.Enum(
        'SLIDE', 'SWING', 'SEESAW', 'ZIPLINE', 'SAND_PLAY', 'TRAMPOLINE', 'CLIMBING', 'WATER_PLAY',
        name='equipment_type',
    )

    # ARRAY(Enum(...))는 autogenerate가 enum 타입 생성을 빠뜨리므로 먼저 명시적으로 생성한다.
    for enum_type in (surface_type, shade_level, restroom_type, parking_type, fence_type, equipment_type):
        enum_type.create(bind, checkfirst=True)

    op.add_column('playgrounds', sa.Column('surface_types', postgresql.ARRAY(surface_type), nullable=True))
    op.add_column('playgrounds', sa.Column('shade_level', shade_level, nullable=True))
    op.add_column('playgrounds', sa.Column('restroom', restroom_type, nullable=True))
    op.add_column('playgrounds', sa.Column('parking', parking_type, nullable=True))
    op.add_column('playgrounds', sa.Column('has_water_fountain', sa.Boolean(), nullable=True))
    op.add_column('playgrounds', sa.Column('has_cctv', sa.Boolean(), nullable=True))
    op.add_column('playgrounds', sa.Column('fence', fence_type, nullable=True))
    op.add_column('playgrounds', sa.Column('stroller_accessible', sa.Boolean(), nullable=True))
    op.add_column('playgrounds', sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True))
    op.add_column('playgrounds', sa.Column('equipment', postgresql.ARRAY(equipment_type), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playgrounds', 'equipment')
    op.drop_column('playgrounds', 'wheelchair_accessible')
    op.drop_column('playgrounds', 'stroller_accessible')
    op.drop_column('playgrounds', 'fence')
    op.drop_column('playgrounds', 'has_cctv')
    op.drop_column('playgrounds', 'has_water_fountain')
    op.drop_column('playgrounds', 'parking')
    op.drop_column('playgrounds', 'restroom')
    op.drop_column('playgrounds', 'shade_level')
    op.drop_column('playgrounds', 'surface_types')
    # ### end Alembic commands ###
