"""add playground edit logs

Revision ID: e24684e82493
Revises: 2ab97c2eacc9
Create Date: 2026-08-04 21:32:47.781334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e24684e82493'
down_revision: Union[str, None] = '2ab97c2eacc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground_edit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playground_id', sa.UUID(), nullable=False),
    sa.Column('editor_id', sa.UUID(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playground_id'], ['playgrounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playground_edit_logs')
    # ### end Alembic commands ###
